### PR TITLE
Add spanish strings' translations

### PR DESCRIPTION
**Pull request by NachoJusticia**
Hi, I have added the **spanish** language to i18n translations. I hope you like it!

### CODE REVIEW

**Comment by NachoJusticia** [comment]
I am software developer, I program mainly web apps using nodejs and react-native. I like your application and I hope I can do more Pull Requests to the project in order to improve the app or develop new features.
👍

**Comment by filippofilip95** [comment]
HI, thanks for adding Spanish language :)
I Am happy that you like my app and that you want to do more Pull Requests.
I'll write possible improvements or new features of app to issue #10, created by you :)

**Comment by filippofilip95** [comment]
App  with Spanish language is now live on Google Play :)

**Comment by NachoJusticia** [comment]
Oh nice! :) 
Your welcome!

**Pull request merged**
